### PR TITLE
bed_shape changed to 235x235 in Stock profiles.

### PR DESCRIPTION
**Pull request by garvamel**
I was having with a 210x210 print. The skirt was being printed outside the bed every time along the X axis when Y = 0 and along the Y axis when X = 0. I realized the bed was set to 220x220, which moves the center of the bed to the front and to the left which effectively leaves the front and left of the part hanging. I only replaced the Stock profiles, since I don't know what mods the other versions have. Cheers and thanks for the awesome profiles, they work great!

### CODE REVIEW

**Comment by sn4k3** [comment]
Lower bed shape was due clips and margin, but yes the correct is 235, thanks for pointing out

**Comment by garvamel** [comment]
I was hitting the clips with 220 and also with the skirt with 235. Because of this it seems would be correct to offset the origin a bit since the part is still not centered even after correcting the bed size. I will test the placement and make a new PR after.

**Comment by sn4k3** [comment]
Please also test new feature, read 1.2. from github and pull new printers

**Comment by garvamel** [comment]
will do!

**Comment by garvamel** [comment]
the model looks bangin'. Thanks a lot! I'm trying to put it inside the .app on macOS, but it seems PrusaSlicer does not let you navigate to it to find it.

**Comment by sn4k3** [comment]
on macos probably you need to put the stl externally and reference it under the settings

**Comment by garvamel** [comment]
I'm updating the readme with the procedure I used to keep it tidy.

**Pull request merged**
